// auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOAD_USER = 'LOAD_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
// config
export const DARK_MODE = 'DARK_MODE';
// alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// profile
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
//eduhub profile
export const GET_EDUHUB_PROFILE = 'GET_EDUHUB_PROFILE';
export const EDUHUB_PROFILE_ERROR = 'EDUHUB_PROFILE_ERROR';
// dept profile
export const GET_DEPT_PROFILE = 'GET_DEPT_PROFILE';
export const GET_DEPT_PROFILE_SUCCESS = 'GET_DEPT_PROFILE_SUCCESS';
export const DEPT_PROFILE_ERROR = 'DEPT_PROFILE_ERROR';
export const DEPT_PROFILE_ERROR_404 = 'DEPT_PROFILE_ERROR_404';
// library profile
export const LIBEARY_LOAD = 'LIBEARY_LOAD';
export const LIBEARY_LOAD_FAIL = 'LIBEARY_LOAD_FAIL';
export const CREATE_LIBRARY_SUCCESS = 'CREATE_LIBRARY_SUCCESS';
export const CREATE_LIBRARY_FAIL = 'CREATE_LIBRARY_FAIL';
export const GET_ALL_BOOKS = 'GET_ALL_BOOKS';
export const GET_ALL_BOOKS_FAIL = 'GET_ALL_BOOKS_FAIL';
// library admin
export const LIBEARY_ADMIN_LOAD = 'LIBEARY_ADMIN_LOAD'
export const LIBEARY_ADMIN_LOAD_FAIL = 'LIBEARY_ADMIN_LOAD_FAIL'
export const GET_ADMIN_ALL_MEMBERS = 'GET_ADMIN_ALL_MEMBERS'
export const GET_ADMIN_ALL_MEMBERS_FAIL = 'GET_ADMIN_ALL_MEMBERS_FAIL'
export const GET_ADMIN_CONNECTED_USER = 'GET_ADMIN_CONNECTED_USER'
export const GET_ADMIN_CONNECTED_USER_FAIL = 'GET_ADMIN_CONNECTED_USER_FAIL'
export const GET_ADMIN_ALL_BOOKS = 'GET_ADMIN_ALL_BOOKS'
export const GET_ADMIN_ALL_BOOKS_FAIL = 'GET_ADMIN_ALL_BOOKS_FAIL'
export const GET_ADMIN_ALL_RESOURCES = 'GET_ADMIN_ALL_RESOURCES'
export const GET_ADMIN_ALL_RESOURCES_FAIL = 'GET_ADMIN_ALL_RESOURCES_FAIL'
export const GET_ADMIN_ALL_TRX = 'GET_ADMIN_ALL_TRX'
export const GET_ADMIN_ALL_TRX_FAIL = 'GET_ADMIN_ALL_TRX_FAIL'
export const GET_ADMIN_ALL_BOOK_TRX = 'GET_ADMIN_ALL_BOOK_TRX'
export const GET_ADMIN_ALL_BOOK_TRX_FAIL = 'GET_ADMIN_ALL_BOOK_TRX_FAIL'
export const GET_ADMIN_ALL_RESOURCE_TRX = 'GET_ADMIN_ALL_RESOURCE_TRX'
export const GET_ADMIN_ALL_RESOURCE_TRX_FAIL = 'GET_ADMIN_ALL_RESOURCE_TRX_FAIL'
// test
export const TEST_LOAD = 'TEST_LOAD';
export const TEST_LOAD_FAIL = 'TEST_LOAD_FAIL';
