// auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOAD_USER = 'LOAD_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
// config
export const DARK_MODE = 'DARK_MODE';
// alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// profile
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
//eduhub profile
export const GET_EDUHUB_PROFILE = 'GET_EDUHUB_PROFILE';
export const EDUHUB_PROFILE_ERROR = 'EDUHUB_PROFILE_ERROR';
// dept profile
export const GET_DEPT_PROFILE = 'GET_DEPT_PROFILE';
export const GET_DEPT_PROFILE_SUCCESS = 'GET_DEPT_PROFILE_SUCCESS';
export const DEPT_PROFILE_ERROR = 'DEPT_PROFILE_ERROR';
export const DEPT_PROFILE_ERROR_404 = 'DEPT_PROFILE_ERROR_404';
// library profile
export const LIBEARY_LOAD = 'LIBEARY_LOAD';
export const LIBEARY_LOAD_FAIL = 'LIBEARY_LOAD_FAIL';
export const CREATE_LIBRARY_SUCCESS = 'CREATE_LIBRARY_SUCCESS';
export const CREATE_LIBRARY_FAIL = 'CREATE_LIBRARY_FAIL';
export const GET_ALL_BOOKS = 'GET_ALL_BOOKS';
export const GET_ALL_BOOKS_FAIL = 'GET_ALL_BOOKS_FAIL';

// test
export const TEST_LOAD = 'TEST_LOAD';
export const TEST_LOAD_FAIL = 'TEST_LOAD_FAIL';
//Dept Settings
export const SET_INFO = 'SET_INFO';
export const SET_CONTACT = 'SET_CONTACT';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_DEPT_MAP = 'SET_DEPT_MAP';
export const SET_DETAIL_SECTION = 'SET_DETAIL_SECTION';
export const SET_MEMBER_SECTION = 'SET_MEMBER_SECTION';
export const SET_CONTROLLER_SECTION = 'SET_CONTROLLER_SECTION';
export const SET_CREATE_SECTION = 'SET_CREATE_SECTION';
export const SET_DETAIL_SECTION_EDIT_OPTION='SET_DETAIL_SECTION_EDIT_OPTION';
export const SET_DETAIL_SECTION_BUTTON_VALUE='SET_DETAIL_SECTION_BUTTON_VALUE';
export const SET_CONTACT_PHONE_ADD = 'SET_CONTACT_PHONE_ADD';
export const SET_CONTACT_MOBILE_ADD = 'SET_CONTACT_MOBILE_ADD';
export const SET_CONTACT_EMAIL_ADD = 'SET_CONTACT_EMAIL_ADD';
export const SET_FORM_DATA ='SET_FORM_DATA';
export const SET_NEW_CONTACT_PHONE_DATA = 'SET_NEW_CONTACT_PHONE_DATA';
export const SET_NEW_CONTACT_MOBILE_DATA = 'SET_NEW_CONTACT_MOBILE_DATA';
export const SET_NEW_CONTACT_EMAIL_DATA = 'SET_NEW_CONTACT_EMAIL_DATA';
export const SET_CONTACTS_DATA = 'SET_CONTACTS_DATA';
